tron1_isaacgym:
  model_name: "policy_1.pt"
  framework: "isaacgym"
  rows: 4
  cols: 3
  dt: 0.005
  decimation: 4
  num_observations: 27
  observations: ["ang_vel", "gravity_vec", "commands", "dof_pos", "dof_vel", "actions"]
  observations_history: [0]
  clip_obs: 100.0
  clip_actions_lower: [-100, -100, -100,
                       -100, -100, -100]
  clip_actions_upper: [100, 100, 100,
                       100, 100, 100]
  rl_kp: [20, 20, 20,
          20, 20, 20]
  rl_kd: [0.5, 0.5, 0.5,
          0.5, 0.5, 0.5]
  fixed_kp: [80, 80, 80,
             80, 80, 80]
  fixed_kd: [3, 3, 3,
             3, 3, 3]
  hip_scale_reduction: 0.5
  hip_scale_reduction_indices: [0, 3]
  num_of_dofs: 6
  action_scale: 0.25
  lin_vel_scale: 2.0
  ang_vel_scale: 0.25
  dof_pos_scale: 1.0
  dof_vel_scale: 0.05
  commands_scale: [2.0, 2.0, 1.0]
  torque_limits: [30.0, 30.0, 30.0,
                  30.0, 30.0, 30.0]
  default_dof_pos: [ 0.000, 0.0000, 0.0000,
                     0.000, 0.0000, 0.0000]
  joint_controller_names: [ "ABAD_L_controller", "HIP_L_controller", "KNEE_L_controller",
                            "ABAD_R_controller", "HIP_R_controller", "KNEE_R_controller" ]
